# Component documentation and configuration
status: 'production'
classBase: 'btn-group'
displayName: 'Button Group'
flavours:
  - base
dependencies:
  - core

# Generates the `Data` table
schema:
  title:
    type: string
    description: "Not output"
  buttons:
    type: array
    description: "Passes a group of buttons to the button component"

# Generates the `Usage` table
usage:
  - class: .btn-group
    required: True
    elements:
      - div
    outcome: Defines the Button Group component
    comments: Wrapping element, adds margin at bottom
