# Component documentation and configuration
status: 'production'
classBase: 'c-link-complex'
displayName: 'Link Complex'
flavours:
  - base
dependencies:
  - core

# Generates the `Data` table
schema:
  title:
    type: string
    description: ""

# Generates the `Usage` table
usage:
  - class: .c-link-complex
    required: True
    elements:
      - div
    outcome: Defines the Link Complex component
    comments: Wrapping element, adds margin at bottom
