# These values will be passed in to the example, using the correct markup
title: 'Product Card'
status: 'prototype'
states:
  - title: 'Simple'
    intro: 'This is a short card intro'
    url: 'http://google.com'
    3d: True
    features:
      - 'No monthly account fee.'
      - 'No transaction fees unless you need to visit a branch.'
      - 'Your statements live in internet banking.'
  - title: 'Image visual'
    header: True
    intro: 'This is a short card intro'
    url: 'http://google.com'
    link_text: 'Link text'
    class: 'card--visual-float@medium width-3/4'
    3d: True
    features:
      - 'No monthly account fee.'
      - 'No transaction fees unless you need to visit a branch.'
      - 'Your statements live in internet banking.'
    visual:
      img:
        alt: 'Alt text'
  - title: 'Rate visual'
    header: True
    intro: 'The interest earning transaction account'
    url: 'http://google.com'
    link_text: 'Link text'
    class: 'card--visual-float@medium width-3/4'
    3d: True
    features:
      - 'No monthly account fee.'
      - 'No transaction fees unless you need to visit a branch.'
      - 'Your statements live in internet banking.'
    visual:
      rate:
        value: '4.50'
        terms: 'Minimum equity 20%.'
