# Component documentation and configuration
status: 'production'
classBase: 'c-related-content'
displayName: 'Related Content'
flavours:
  - base
dependencies:
  - core

# Generates the `Data` table
schema:
  title:
    type: string
    description: ""

# Generates the `Usage` table
usage:
  - class: .c-related-content
    required: True
    elements:
      - div
    outcome: Defines the Related Content component
    comments: Wrapping element, adds margin at bottom
