# Component documentation and configuration
status: 'production'
classBase: 'rate'
displayName: 'Rate'
flavours:
  - base
dependencies:
  - core

# Generates the `Data` table
schema:
  title:
    type: string
    description: ""

# Generates the `Usage` table
usage:
  - class: .rate
    required: True
    elements:
      - div
    outcome: Defines the Rate component
    comments: Wrapping element, adds margin at bottom
