title: 'Base'
status: 'development'
states:
  - title: 'Base'
    buttons:
      - text: 'Find out more'
        url: '/url/to/page'
        theme: 'primary'
      - text: 'Apply now'
        url: '/url/to/page'
        theme: 'secondary'
      - text: 'Apply now'
        url: '/url/to/page'
        theme: 'blue'
      - text: 'Read more'
        url: '/url/to/page'
        theme: 'white'
      - text: 'Find out more'
        url: '/url/to/page'
        theme: 'grey+green'
