# Component documentation and configuration
status: 'production'
classBase: 'c-cta-block'
displayName: 'Cta Block'
flavours:
  - base
dependencies:
  - core

# Generates the `Data` table
schema:
  title:
    type: string
    description: ""

# Generates the `Usage` table
usage:
  - class: .c-cta-block
    required: True
    elements:
      - div
    outcome: Defines the Cta Block component
    comments: Wrapping element, adds margin at bottom
