# Component documentation and configuration
status: 'production'
classBase: 'tile'
displayName: 'Tile'
flavours:
  - base
dependencies:
  - core

# Generates the `Data` table
schema:
  title:
    type: string
    description: 'Snappy headling'
  heading_class:
    type: 'string'
    description: 'Class to alter heading colour if need be'
  body:
    type: string
    description: 'Short paragraph'
  link:
    type: array
    description: 'Text and url tile should link to'


# Generates the `Usage` table
usage:
  - class: .tile
    required: True
    elements:
      - div
    outcome: Defines the Tile component
    comments: Wrapping element, adds margin at bottom
