# These values will be passed in to the example, using the correct markup
title: 'Interactive Card'
status: 'prototype'
state:
  title: 'My awesome interactive card!'
  subtitle: 'It does fancy things...'
  excerpt: 'This is a short card intro'
  url: 'http://google.com'
  img:
    src: 'path/to/image'
    alt: 'Alt text'

